language:
  - python

compiler:
  - gcc

python:
  - 2.6
  - 2.7

branches:
  except:
    - master

before_install:
  - sudo apt-get install -qq libxml2-dev libxslt1-dev

install:
  - pip install -r requirements-test.txt

script:
  - python setup.py test -q
